// This file is auto-generated by scripts/extract-fallback-copy.mjs.
// Do not edit it manually—update docs/fallback-texts.md instead and run `pnpm fallback:sync`.
export const FALLBACK_TEXTS = {
  "sessionTitle": {
    "defaultFromDate": "Session on {DATE}"
  },
  "introFlow": {
    "returningGreetingWithTitles": "Welcome back—I'm keeping your stories about {TITLES} safe for you.",
    "returningGreetingDefault": "Welcome back—your archive is open and I'm ready whenever you are.",
    "firstTimeGreeting": "Hi, I'm DadsBot. I'm here to help you capture the memories you want to keep.",
    "latestDetailReminder": "The last thing you shared was about {DETAIL}.",
    "noDetailPromise": "I'll remember every detail you share from this moment on.",
    "returningInvitation": "When you are ready, …",
    "firstSessionInvitation": "When you feel ready, …",
    "defaultContinuationQuestion": "Where would you like to pick up the story?",
    "firstSessionQuestion": "Would you start by telling me the first memory you'd like to save together?",
    "clientFallback": "Welcome back. I remember everything you have trusted me with. Tell me one new detail you would like to explore now."
  },
  "questions": {
    "detailGuard": "When you think about {DETAIL}, what else stands out now?",
    "promptPool": [
      "Could you set the scene for me—where were you when this memory took place?",
      "Who else shared that moment with you, and what were they doing?",
      "What was the very first thing you noticed as it unfolded?",
      "What feeling rushed in right away?",
      "Is there a small sound or scent that still brings it back to you?",
      "Was there an object in the room that now holds extra meaning for you?",
      "What was happening just a few moments before everything began?",
      "How did the light or weather color that scene for you?",
      "What voices or music drifted through the background?",
      "Was there a taste or texture that anchors the memory for you?"
    ],
    "finalGuard": "Tell me one detail you have not shared with me yet."
  },
  "askTurn": {
    "firstSessionGreeting": "Hi, I'm DadsBot. I'm here to help you save the stories and small details your family will want to revisit. When it feels right, would you start with a memory you'd like me to remember?",
    "returningWithHighlight": "Welcome back. I'm still holding onto what you told me about {HIGHLIGHT}. Let's add another chapter to your archive.",
    "returningDefault": "Welcome back—your story archive is open and I'm keeping track of everything you've trusted me with.",
    "providerException": "Who else was there? Share a first name and one detail about them."
  }
} as const;

export type FallbackTexts = typeof FALLBACK_TEXTS;
